PackageIdentifier: YuniqueUnic.schemaui-cli
PackageVersion: 0.4.3
Installers:
  - Architecture: x64
    InstallerType: zip
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: schemaui.exe
        PortableCommandAlias: schemaui
    Commands:
      - schemaui
    InstallerUrl: https://github.com/YuniqueUnic/schemaui/releases/download/schemaui-cli-v0.4.3/schemaui-x86_64-pc-windows-msvc.zip
    InstallerSha256: 2AF6745921CE67FDF888A5D137DD19CDC92568991237B06082A36A9EED6247C9
  - Architecture: arm64
    InstallerType: zip
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: schemaui.exe
        PortableCommandAlias: schemaui
    Commands:
      - schemaui
    InstallerUrl: https://github.com/YuniqueUnic/schemaui/releases/download/schemaui-cli-v0.4.3/schemaui-aarch64-pc-windows-msvc.zip
    InstallerSha256: D8A9AA8B78E45E403B53B004D797957DEF5D97C83185C1227C3C8EBF2301C1DE
ManifestType: installer
ManifestVersion: 1.12.0
