// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PreviewRequest { data: Record<string, unknown>, format: string, pretty: boolean, }
