// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs).
// The Rust source of truth lives in `src/web/session.rs::SessionResponse`.

export interface SessionResponse {
    title: string | null;
    // Raw UiAst tree from the backend; the web UI wraps this into its own
    // UiAst type in `web/ui/src/types.ts`.
    ui_ast: Record<string, unknown>;
    data: Record<string, unknown>;
    formats: Array<string>;
    // Optional UiLayout tree; the web UI also reinterprets this locally.
    layout: Record<string, unknown> | null;
}
