// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebBlueprint } from "./WebBlueprint";

export interface SessionResponse { title: string | null, blueprint: WebBlueprint, data: Record<string, unknown>, formats: Array<string>, }
