// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldError } from "./FieldError";

export interface ValidationResponse { ok: boolean, errors: Array<FieldError>, }
