// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebSection } from "./WebSection";

export interface WebCompositeVariant { id: string, title: string, description: string | null, schema: Record<string, unknown>, is_object: boolean, sections: Array<WebSection>, }
