// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebCompositeMode } from "./WebCompositeMode";
import type { WebCompositeVariant } from "./WebCompositeVariant";

export type WebFieldKind = { "type": "string" } | { "type": "integer" } | { "type": "number" } | { "type": "boolean" } | { "type": "enum", options: Array<string>, } | { "type": "array", items: WebFieldKind, } | { "type": "json" } | { "type": "composite", mode: WebCompositeMode, variants: Array<WebCompositeVariant>, } | { "type": "key_value", key_title: string, key_description: string | null, value_title: string, value_description: string | null, value_kind: WebFieldKind, };
