// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebFieldKind } from "./WebFieldKind";

export interface WebField { name: string, label: string, pointer: string, description: string | null, required: boolean, kind: WebFieldKind, default_value: Record<string, unknown> | null, }
