// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebField } from "./WebField";

export interface WebSection { id: string, title: string, description: string | null, fields: Array<WebField>, sections: Array<WebSection>, }
